ХНУРЕ:
  name: Харківський національний університет радіоелектроніки
  name-en: Kharkiv National University of Radioelectronics
  edu-programs:
    ПЗПІ:
      name-long: Інженерія програмного забезпечення
      department-gen: Програмної інженерії
      code: 121 # TODO: change to F2?
    КУІБ:
      name-long: Управління інформаційною безпекою
      department-gen: Інфокомунікаційної інженерії ім. В. В. Поповського
      code: 125 # TODO: change to F5?
      description: Кібербезпека та захист інформації
    КНТ:
      name-en: CST # computer sciences and technologies
      name-long: Комп'ютерні науки та технології
      department-gen: Системотехніки
      department-en: ST
      code: 122
  subjects:
    DMT: Decision making theory
    ODS: Основи Dаtа Sсіеnсе # NOTE: Eng O here
    ІМ: Іноземна мова
    ІТР: Information Technologies of Reengineering
    ІТРОІ: Інтернет-технології Розподіленої Обробки Інформації
    АВпЗ: Аналіз вимог до програмного забезпечення
    АДан: Аналітика даних
    АКтаК: Архітектура комп'ютера та комп'ютерних мереж
    АТСД: Алгоритми та структури даних
    АтаРК: Аналіз та рефакторинг коду
    БД: Бази даних
    БЖД: Безпека життєдіяльності
    ВДІТБ: Введення до ІТ-бізнесу # NOTE: all in UA
    ВМ: Вища математика
    ГТГ: Гіпертекст та гіпермедіа
    ДМ: Дискретна математика
    ДПК: Динаміка Проектних Команд
    ЕРВ: Електрорадіовимірювання
    КДМА: Комп'ютерна дискретна математика
    КЗВШ: Креативність з використанням штучного інтелекту
    КМ: Комп`ютерні мережі
    ЛМВ: Людино-машинна взаємодія
    ЛМтБ: Локальні мережі та їх безпека # бидло не знає що українською "їхня"
    МОКр: Математичні основи криптології
    МОТДО: Методи оптимізаціі та дослідження операцій
    МППС: Methodologies of designing software systems
    МС: Моделювання систем
    ОІМ: Основи IP-мереж
    ООАПС: Об'єктно-орієнтований аналіз в проектуванні систем
    ООП: Об'єктно-орієнтоване програмування
    ОП: Основи права
    ОПІ: Основи програмноі інженеріі
    ОПНJ: Основи програмування на Java
    ОПр: Основи програмування
    ОРвІТ: Оцінка Ризиків в IT-проектах
    ОС: Операційні системи
    ОТК: Основи теорії кіл
    ПБІП: Проектування та балансування ігрового процесу
    ПВJ: Поглиблене вивчення Java
    ПЕСЕ: Психологія екстремальних стосунків та ефективної адаптації
    ПНП: Програмування на платформі .NЕТ
    ПП: Проектний практикум
    ПРОГ: Програмування
    ПарП: Параллельне програмування
    СА: Системний аналіз
    СМП: Скриптові мови програмування
    СОАПЗ: Сервіс-Орієнтована Архітектура Програмного Забезпечення
    СРБД: Серверні рішення баз даних
    СхТ: Схемотехніка
    ТВО: Технології Високопродуктивних Обчислень
    ТЗІ: Технології захисту інформації
    ТЙтаМ: Теорія ймовірностей та математична # TODO: what?
    ТКП: Технології комп`ютерного проєктування
    УФМ: Українське фахове мовлення
    ФІЗ: Фізика
    ФІЛ: Філософія
    ФВС: Фізичне виховання та спорт
    ХТ: Хмарні технології
    NoSQL: NoSQL-системи
    АПЗ: Архітектура програмного забезпечення
    ВSAP: Введення до SAP-технологій
    ВМПтФ: Високорівневі мови програмування та фреймворки
    ІМпк: Іноземна мова для професійної комунікації
    ІНТ: Історія науки і техніки
    Лог: Логіка
    МППЗ: Менеджмент проектів програмного забезпечення
    МОТІ: Методи оптимізації та теорія ігр
    ОІДт: Обробка ігрових даних та звітів
    ПвІТ: Підприємництво в ІТ
    ПВJS: Поглиблене вивчення JavaScript
    ПPyt: Програмування мовою Python
    РNet: Робота з даними на платформі .Net
    РХЗ: Розробка хмарних застосувань в AZURE
